version: '3.4'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379
    environment: 
      - REDIS_PASSWORD=<PASS>
    networks: 
      - reduct_network

  reductapi:
    container_name: reductapi
    image: reductapi
    ports:
      - 6766:80
    networks:
      - reduct_network
  
  reductui:
    container_name: reductui
    image: reductui
    ports: 
      - 6767:8080
    networks: 
      - reduct_network

networks: 
  reduct_network:
    driver: bridge